### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by cadamini** [tobilen/csv-tz-converter#11]
I just needed to use your script again.

The command `convert-timezone -f "source.csv" -d dd.MM.yyyy -i "Europe/Berlin" -t "target.csv"`

fails with 

**Unhandled rejection RangeError: Invalid time value**
    at format (/usr/local/lib/node_modules/csv-tz-converter/node_modules/date-fns/format/index.js:390:11)
    at /usr/local/lib/node_modules/csv-tz-converter/convert.js:16:9
    at processLineByLine (/usr/local/lib/node_modules/csv-tz-converter/node_modules/csvtojson/v2/Result.js:107:23)
    at /usr/local/lib/node_modules/csv-tz-converter/node_modules/csvtojson/v2/Result.js:49:17
    at Promise._execute (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/promise.js:103:10)
    at Result.processResult (/usr/local/lib/node_modules/csv-tz-converter/node_modules/csvtojson/v2/Result.js:47:16)
    at /usr/local/lib/node_modules/csv-tz-converter/node_modules/csvtojson/v2/Converter.js:150:37
    at tryCatcher (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/csv-tz-converter/node_modules/bluebird/js/release/async.js:86:9)

### Sample file

```
Queue;Date;Time;Offered;Handled;AHT;Channel
Inbound;01.10.2020;01:00;0;0;0;calls
Inbound;01.10.2020;01:15;0;0;0;calls
Inbound;01.10.2020;01:30;0;0;0;calls
Inbound;01.10.2020;01:45;0;0;0;calls
```

### Notes

Th default format like 04/25/2016 without -d is working.

**Comment by cadamini** [comment]
Tested with 31.05.2020, must be related to my inputs.

**Comment by cadamini** [comment]
Or related to an update. It's definietely working now.
